table _Measures
	lineageTag: 5a601bc2-4360-4303-8865-9cf4b154b7c5

	measure trailer_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Trailer_bdx,
			        Fact_Trailer_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Trailer_bdx[CancellationStatus] = "No Cancellation" 
			    ),
			    Fact_Trailer_bdx[Base_Installment_Premium] + Fact_Trailer_bdx[Upgrade_Installment_Premium]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Trailer_bdx,
			            (
			                Fact_Trailer_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Trailer_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Trailer_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Trailer_bdx[Base_Installment_Premium] + Fact_Trailer_bdx[Upgrade_Installment_Premium]
			    ),
			    USERELATIONSHIP(
			        Fact_Trailer_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Trailer_bdx,
			            Fact_Trailer_bdx[type] = "Cancelled" &&
			            (
			            Fact_Trailer_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Trailer_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			        Fact_Trailer_bdx[Base_Installment_Premium] + Fact_Trailer_bdx[Upgrade_Installment_Premium]
			    ),
			    USERELATIONSHIP(
			        Fact_Trailer_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 2. Trailer
		lineageTag: b4050ae5-3a52-42ed-9f77-68da64dcb248

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ipt_trailer_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Trailer_bdx,
			        Fact_Trailer_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Trailer_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Trailer_bdx[Base_Installment_IPT] + Fact_Trailer_bdx[Upgrade_Installment_IPT]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Trailer_bdx,
			            (
			                Fact_Trailer_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Trailer_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Trailer_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Trailer_bdx[Base_Installment_IPT] + Fact_Trailer_bdx[Upgrade_Installment_IPT]
			    ),
			    USERELATIONSHIP(
			        Fact_Trailer_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Trailer_bdx,
			            Fact_Trailer_bdx[type] = "Cancelled" &&
			            (
			            Fact_Trailer_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Trailer_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Trailer_bdx[Base_Installment_IPT] + Fact_Trailer_bdx[Upgrade_Installment_IPT]
			    ),
			    USERELATIONSHIP(
			        Fact_Trailer_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 2. Trailer
		lineageTag: dbcc961c-265d-4b89-81e7-896ced0c5359

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure pl_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_Premium_PL] + Fact_Memberships_bdx[Upgrade_Installment_Premium_PL]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_Premium_PL] + Fact_Memberships_bdx[Upgrade_Installment_Premium_PL]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Memberships_bdx[Base_Installment_Premium_PL] + Fact_Memberships_bdx[Upgrade_Installment_Premium_PL]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN
			
			RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: 0a9af22a-625e-4f58-90bf-52e12ca4a082

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ipt_pl_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_IPT_PL] + Fact_Memberships_bdx[Upgrade_Installment_IPT_PL]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_IPT_PL] + Fact_Memberships_bdx[Upgrade_Installment_IPT_PL]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Memberships_bdx[Base_Installment_IPT_PL] + Fact_Memberships_bdx[Upgrade_Installment_IPT_PL]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: f8e6fc80-79a8-4e4e-aa74-b45efe2df403

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure pa_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_Premium_PA] + Fact_Memberships_bdx[Upgrade_Installment_Premium_PA]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_Premium_PA] + Fact_Memberships_bdx[Upgrade_Installment_Premium_PA]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			            )
			        ),
			        Fact_Memberships_bdx[Base_Installment_Premium_PA] + Fact_Memberships_bdx[Upgrade_Installment_Premium_PA]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: 1f28b8ae-ede7-4e5d-9fd2-f265e50abf40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ipt_pa_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_IPT_PA] + Fact_Memberships_bdx[Upgrade_Installment_IPT_PA]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_IPT_PA] + Fact_Memberships_bdx[Upgrade_Installment_IPT_PA]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			            )
			        ),
			        Fact_Memberships_bdx[Base_Installment_IPT_PA] + Fact_Memberships_bdx[Upgrade_Installment_IPT_PA]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: fe34590b-2489-416b-80b1-1c08bfe40d91

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure fr_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_Premium_FR] + Fact_Memberships_bdx[Upgrade_Installment_Premium_FR]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_Premium_FR] + Fact_Memberships_bdx[Upgrade_Installment_Premium_FR]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Memberships_bdx[Base_Installment_Premium_FR] + Fact_Memberships_bdx[Upgrade_Installment_Premium_FR]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: c3d0a5a9-474f-4cc6-9012-5942d39508e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ipt_fr_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_IPT_FR] + Fact_Memberships_bdx[Upgrade_Installment_IPT_FR]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_IPT_FR] + Fact_Memberships_bdx[Upgrade_Installment_IPT_FR]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Memberships_bdx[Base_Installment_IPT_FR] + Fact_Memberships_bdx[Upgrade_Installment_IPT_FR]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: 56726f20-4a11-48fb-a67e-8b93dde791a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure vet_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Vet_bdx,
			        Fact_Vet_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Vet_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Vet_bdx[Base_Installment_Premium]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Vet_bdx,
			            (
			                Fact_Vet_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Vet_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Vet_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Vet_bdx[Base_Installment_Premium]
			    ),
			    USERELATIONSHIP(
			        Fact_Vet_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Vet_bdx,
			            Fact_Vet_bdx[type] = "Cancelled" &&
			            (
			            Fact_Vet_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Vet_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			        Fact_Vet_bdx[Base_Installment_Premium]
			    ),
			    USERELATIONSHIP(
			        Fact_Vet_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 3. Vet
		lineageTag: 4f5298a3-a6a3-4661-9293-abd131f12c00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ipt_vet_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Vet_bdx,
			        Fact_Vet_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Vet_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Vet_bdx[Base_Installment_IPT]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Vet_bdx,
			            (
			                Fact_Vet_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Vet_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Vet_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Vet_bdx[Base_Installment_IPT]
			    ),
			    USERELATIONSHIP(
			        Fact_Vet_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Vet_bdx,
			            Fact_Vet_bdx[type] = "Cancelled" &&
			            (
			            Fact_Vet_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Vet_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Vet_bdx[Base_Installment_IPT]
			    ),
			    USERELATIONSHIP(
			        Fact_Vet_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 3. Vet
		lineageTag: 2bc433c8-f073-4cf8-ac31-dff65468bc4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure commission_vet_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Vet_bdx,
			        Fact_Vet_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Vet_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Vet_bdx[Base_Installment_Commission]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Vet_bdx,
			            (
			                Fact_Vet_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Vet_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Vet_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Vet_bdx[Base_Installment_Commission]
			    ),
			    USERELATIONSHIP(
			        Fact_Vet_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Vet_bdx,
			            Fact_Vet_bdx[type] = "Cancelled" &&
			            (
			            Fact_Vet_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Vet_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Vet_bdx[Base_Installment_Commission]
			    ),
			    USERELATIONSHIP(
			        Fact_Vet_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 3. Vet
		lineageTag: 7905e6e4-3cb7-4c6d-8ab7-8b60ce9d1bb9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure admin_fee_vet_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Vet_bdx,
			        Fact_Vet_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Vet_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Vet_bdx[Base_Installment_AdminFee]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Vet_bdx,
			            (
			                Fact_Vet_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Vet_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Vet_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Vet_bdx[Base_Installment_AdminFee]
			    ),
			    USERELATIONSHIP(
			        Fact_Vet_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Vet_bdx,
			            Fact_Vet_bdx[type] = "Cancelled" &&
			            (
			            Fact_Vet_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Vet_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Vet_bdx[Base_Installment_AdminFee]
			    ),
			    USERELATIONSHIP(
			        Fact_Vet_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 3. Vet
		lineageTag: 45dd6801-b33b-47e0-8f86-0a5c1a34417b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure commission_trailer_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Trailer_bdx,
			        Fact_Trailer_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Trailer_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Trailer_bdx[Base_Installment_Commission] + Fact_Trailer_bdx[Upgrade_Installment_Commission]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Trailer_bdx,
			            (
			                Fact_Trailer_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Trailer_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Trailer_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Trailer_bdx[Base_Installment_Commission] + Fact_Trailer_bdx[Upgrade_Installment_Commission]
			    ),
			    USERELATIONSHIP(
			        Fact_Trailer_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Trailer_bdx,
			            Fact_Trailer_bdx[type] = "Cancelled" &&
			            (
			            Fact_Trailer_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Trailer_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Trailer_bdx[Base_Installment_Commission] + Fact_Trailer_bdx[Upgrade_Installment_Commission]
			    ),
			    USERELATIONSHIP(
			        Fact_Trailer_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 2. Trailer
		lineageTag: ac67c132-0c4b-4b6f-aeee-c857c680bf3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure admin_fee_trailer_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Trailer_bdx,
			        Fact_Trailer_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Trailer_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Trailer_bdx[Base_Installment_AdminFee] + Fact_Trailer_bdx[Upgrade_Installment_AdminFee]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Trailer_bdx,
			            (
			                Fact_Trailer_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Trailer_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Trailer_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Trailer_bdx[Base_Installment_AdminFee] + Fact_Trailer_bdx[Upgrade_Installment_AdminFee]
			    ),
			    USERELATIONSHIP(
			        Fact_Trailer_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Trailer_bdx,
			            Fact_Trailer_bdx[type] = "Cancelled" &&
			            (
			            Fact_Trailer_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Trailer_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Trailer_bdx[Base_Installment_AdminFee] + Fact_Trailer_bdx[Upgrade_Installment_AdminFee]
			    ),
			    USERELATIONSHIP(
			        Fact_Trailer_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 2. Trailer
		lineageTag: 490e538a-3d07-4e2f-97e8-368ddf543e1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure commission_fr_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_Commission_FR] + Fact_Memberships_bdx[Upgrade_Installment_Commission_FR]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_Commission_FR] + Fact_Memberships_bdx[Upgrade_Installment_Commission_FR]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Memberships_bdx[Base_Installment_Commission_FR] + Fact_Memberships_bdx[Upgrade_Installment_Commission_FR]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: e95c8d30-92e8-4edb-87c7-c4b54d4c2d5a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure admin_fee_fr_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_Admin_FR] + Fact_Memberships_bdx[Upgrade_Installment_Admin_FR]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_Admin_FR] + Fact_Memberships_bdx[Upgrade_Installment_Admin_FR]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Memberships_bdx[Base_Installment_Admin_FR] + Fact_Memberships_bdx[Upgrade_Installment_Admin_FR]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: 6067cb33-e89a-44e8-a91f-bae2ad9d4282

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure commission_pa_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_Commission_PA] + Fact_Memberships_bdx[Upgrade_Installment_Commission_PA]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_Commission_PA] + Fact_Memberships_bdx[Upgrade_Installment_Commission_PA]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			            )
			        ),
			        Fact_Memberships_bdx[Base_Installment_Commission_PA] + Fact_Memberships_bdx[Upgrade_Installment_Commission_PA]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: 638aa190-7d22-4bc8-b4f7-d67b9bf3d431

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure admin_fee_pa+pl_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_Admin_Generic] + Fact_Memberships_bdx[Upgrade_Installment_Admin_Generic]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_Admin_Generic] + Fact_Memberships_bdx[Upgrade_Installment_Admin_Generic]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Memberships_bdx[Base_Installment_Admin_Generic] + Fact_Memberships_bdx[Upgrade_Installment_Admin_Generic]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: 872798dd-a1fb-4d42-b807-fecd9a5a671a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure commission_pl_payment_total = ```
			
			
			VAR RegularPayments = 
			SUMX(
			    FILTER(
			        Fact_Memberships_bdx,
			        Fact_Memberships_bdx[CancellationStatus] = "Before Cancellation" ||
			        Fact_Memberships_bdx[CancellationStatus] = "No Cancellation"
			    ),
			    Fact_Memberships_bdx[Base_Installment_Commission_PL] + Fact_Memberships_bdx[Upgrade_Installment_Commission_PL]
			)
			
			VAR RemainingPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            (
			                Fact_Memberships_bdx[CancellationStatus] = "After Cancellation" ||
			                Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month"
			            ) &&
			                Fact_Memberships_bdx[type] <> "Cancelled"
			
			        ),
			        Fact_Memberships_bdx[Base_Installment_Commission_PL] + Fact_Memberships_bdx[Upgrade_Installment_Commission_PL]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR CancelledRowPremium = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            Fact_Memberships_bdx,
			            Fact_Memberships_bdx[type] = "Cancelled" &&
			            (
			            Fact_Memberships_bdx[CancellationStatus] = "In Cancellation Month" ||
			            Fact_Memberships_bdx[CancellationStatus] = "Renewal Cancellation"
			            )
			        ),
			    Fact_Memberships_bdx[Base_Installment_Commission_PL] + Fact_Memberships_bdx[Upgrade_Installment_Commission_PL]
			    ),
			    USERELATIONSHIP(
			        Fact_Memberships_bdx[CancellationEffectiveDate_YearMonthNum], 'dim_BDXDate'[MonthYearNum]
			    )
			)
			
			VAR LumpSum = CancelledRowPremium + RemainingPremium
			
			RETURN 
			    RegularPayments + LumpSum
			```
		displayFolder: 1. Memberships
		lineageTag: 2ec78536-dca5-4855-8901-33b3df956376

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure pl_eomonth_table_title =
			
			var _latestDate = MAX(pl_table_EOMonth[Date modified])
			var _previousMonth = EOMONTH(_latestDate, -1)
			RETURN
			"PL Report: End Of " & FORMAT(_previousMonth, "MMMM YYYY")
		displayFolder: 4. EOMonth table titles
		lineageTag: a9482f6f-29e2-4867-b029-f4a02d9bc090

	measure pa_eomonth_table_title =
			
			var _latestDate = MAX(pa_table_EOMonth[Date modified])
			var _previousMonth = EOMONTH(_latestDate, -1)
			RETURN
			"PA Report: End Of " & FORMAT(_previousMonth, "MMMM YYYY")
		displayFolder: 4. EOMonth table titles
		lineageTag: 4c51b5fe-6e57-462f-8990-878744f66e47

	measure fr_eomonth_table_title =
			
			var _latestDate = MAX(fr_table_EOMonth[Date modified])
			var _previousMonth = EOMONTH(_latestDate, -1)
			RETURN
			"FR Report: End Of " & FORMAT(_previousMonth, "MMMM YYYY")
		displayFolder: 4. EOMonth table titles
		lineageTag: 52e8c2b5-e381-484b-a08f-fd8285afaf7b

	measure trailer_eomonth_table_title =
			
			var _latestDate = MAX(trailer_table_EOMonth[Date modified])
			var _previousMonth = EOMONTH(_latestDate, -1)
			RETURN
			"Trailer Report: End Of " & FORMAT(_previousMonth, "MMMM YYYY")
		displayFolder: 4. EOMonth table titles
		lineageTag: 47397bc4-07e1-439f-a14b-94acae806be6

	measure vet_eomonth_table_title =
			
			var _latestDate = MAX(vet_table_EOMonth[Date modified])
			var _previousMonth = EOMONTH(_latestDate, -1)
			RETURN
			"VET Report: End Of " & FORMAT(_previousMonth, "MMMM YYYY")
		displayFolder: 4. EOMonth table titles
		lineageTag: 1b8a5e37-6084-4e6f-af19-67b06cceb6df

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

