table Fact_Trailer_bdx
	lineageTag: d12c5d9b-b9de-4a0e-86af-ddc2cd4bd438

	column reference
		dataType: string
		lineageTag: 30e466f0-02da-458e-9ccf-81a81c23cff5
		summarizeBy: none
		sourceColumn: reference

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column underwritten_month_num
		dataType: int64
		formatString: 0
		lineageTag: e1ad0cab-5e6e-458d-8be3-3ade38320749
		summarizeBy: none
		sourceColumn: underwritten_month_num

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 657039ce-1bad-4a01-ae8c-1c99bc80ee29
		summarizeBy: none
		sourceColumn: type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cancelled_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 45ddc132-0494-4049-8558-382078a8d47e
		summarizeBy: none
		sourceColumn: cancelled_date

		variation Variation
			isDefault
			relationship: eeb02438-f4e6-40ac-95e5-deff0c7e2a4c
			defaultHierarchy: LocalDateTable_b54610e5-3d95-4027-8eb5-9793c69eab29.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column policy_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1d74d97c-406f-49b6-b279-6ea214a662d0
		summarizeBy: none
		sourceColumn: policy_start_date

		variation Variation
			isDefault
			relationship: bed487e1-7cbb-4547-bef0-afde7e377ab6
			defaultHierarchy: LocalDateTable_5c29a0d5-68b5-4363-bee0-4d5418a75082.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column days_used
		dataType: int64
		formatString: 0
		lineageTag: a8f65cf7-f52b-4b1b-8183-8b555f14ab4a
		summarizeBy: sum
		sourceColumn: days_used

		annotation SummarizationSetBy = Automatic

	column days_paid
		dataType: int64
		formatString: 0
		lineageTag: 969c9c04-09a7-4b06-87e9-6a739d9b9b2e
		summarizeBy: sum
		sourceColumn: days_paid

		annotation SummarizationSetBy = Automatic

	column interval
		dataType: string
		lineageTag: 61e2899c-6e4d-4be1-b351-b0de2c1321cd
		summarizeBy: none
		sourceColumn: interval

		annotation SummarizationSetBy = Automatic

	column annual_cost
		dataType: double
		lineageTag: aa45a876-6d32-4184-85e6-3b5b7f2fe184
		summarizeBy: sum
		sourceColumn: annual_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column annual_premium_excl_ipt
		dataType: double
		lineageTag: 3596d602-6a71-494c-a76e-821962a16d8f
		summarizeBy: sum
		sourceColumn: annual_premium_excl_ipt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column annual_net_premium
		dataType: double
		lineageTag: b307a805-3e51-4aac-87a6-6094239a3fe6
		summarizeBy: sum
		sourceColumn: annual_net_premium

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ipt
		dataType: double
		lineageTag: b79f951a-cbaf-494f-be75-4a61d02df778
		summarizeBy: sum
		sourceColumn: ipt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column annual_commision
		dataType: double
		lineageTag: 1423261d-0b7c-4bc1-acfb-c104142b416f
		summarizeBy: sum
		sourceColumn: annual_commision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column admin_fee
		dataType: double
		lineageTag: ea6d33dd-38a0-4502-8e0a-fefd0ab173cd
		summarizeBy: sum
		sourceColumn: admin_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column policy_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0240be92-ef65-4446-b302-2cc29eddce1b
		summarizeBy: none
		sourceColumn: policy_end_date

		variation Variation
			isDefault
			relationship: 5484ac72-2b98-4bcc-a3c5-c21ba24d2d6e
			defaultHierarchy: LocalDateTable_f0d461fc-578d-47af-aa4d-d20b1496375f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IntervalMonths
		dataType: int64
		formatString: 0
		lineageTag: 874a5da5-7532-466c-a273-f65b7d6aa91a
		summarizeBy: sum
		sourceColumn: IntervalMonths

		annotation SummarizationSetBy = Automatic

	column AlignedStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3bfc119-bac9-4a68-ad41-5746d8c5a948
		summarizeBy: none
		sourceColumn: AlignedStart

		variation Variation
			isDefault
			relationship: 3419dbe9-5cc5-446b-81c7-e5c719122a5d
			defaultHierarchy: LocalDateTable_68f27fd3-03fe-46ee-b95d-fb2382bf9948.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PayStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8315f606-2de5-4944-b0ad-f816bf73ea6b
		summarizeBy: none
		sourceColumn: PayStart

		variation Variation
			isDefault
			relationship: b806d774-2abd-4f93-ae97-ef4577b23d6b
			defaultHierarchy: LocalDateTable_3ac2fba5-7504-4cb3-9407-a539f1df4912.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CancellationStatus
		dataType: string
		lineageTag: a2307a2c-1720-4bf9-b354-1683cf8ef0d6
		summarizeBy: none
		sourceColumn: CancellationStatus

		annotation SummarizationSetBy = Automatic

	column InstalmentCount
		dataType: int64
		formatString: 0
		lineageTag: 9f16b1ca-e413-4ba5-aff8-c40276a3920f
		summarizeBy: sum
		sourceColumn: InstalmentCount

		annotation SummarizationSetBy = Automatic

	column Base_Installment_Premium
		dataType: double
		formatString: 0.0000
		lineageTag: 06f50f20-c394-4e3a-8516-5e04a4be2e46
		summarizeBy: sum
		sourceColumn: Base_Installment_Premium

		annotation SummarizationSetBy = Automatic

	column Base_Installment_IPT
		dataType: double
		formatString: 0.0000
		lineageTag: 8f3e0577-ad29-46a7-a5b8-6d46eaaeec66
		summarizeBy: sum
		sourceColumn: Base_Installment_IPT

		annotation SummarizationSetBy = Automatic

	column upgrade_instalment_count
		dataType: double
		formatString: 0
		lineageTag: bd34c43c-05f4-4ff5-ba0a-9155fd185c86
		summarizeBy: sum
		sourceColumn: upgrade_instalment_count

		annotation SummarizationSetBy = Automatic

	column Upgrade_Installment_Premium
		dataType: double
		formatString: 0.0000
		lineageTag: b7574fee-86b6-4722-9964-8f6028305116
		summarizeBy: sum
		sourceColumn: Upgrade_Installment_Premium

		annotation SummarizationSetBy = Automatic

	column Upgrade_Installment_IPT
		dataType: double
		formatString: 0.0000
		lineageTag: db9c1181-e361-4b95-89ac-870ec1e1531d
		summarizeBy: sum
		sourceColumn: Upgrade_Installment_IPT

		annotation SummarizationSetBy = Automatic

	column CancellationEffectiveDate_YearMonthNum
		dataType: int64
		formatString: 0
		lineageTag: 81eca52b-3305-4da1-bed0-886ce30fe480
		summarizeBy: sum
		sourceColumn: CancellationEffectiveDate_YearMonthNum

		annotation SummarizationSetBy = Automatic

	column payment_month_num
		dataType: int64
		formatString: 0
		lineageTag: 3c186f5a-a5de-48b4-b401-4c5daa40c839
		summarizeBy: sum
		sourceColumn: payment_month_num

		annotation SummarizationSetBy = Automatic

	column Effective_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3916d52d-6be2-422d-896e-5683ea7e125a
		summarizeBy: none
		sourceColumn: Effective_Date

		variation Variation
			isDefault
			relationship: 94f48be8-6dba-4ace-ba61-aa1314f06d39
			defaultHierarchy: LocalDateTable_84958d24-9184-4cd5-8e7b-bee3c7ca5289.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Base_Installment_Commission
		dataType: double
		lineageTag: 795b1af3-9b76-479c-b3e5-570316f6b939
		summarizeBy: sum
		sourceColumn: Base_Installment_Commission

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Base_Installment_AdminFee
		dataType: double
		lineageTag: 9a4d2764-9b44-44ae-97fa-100fea2343c6
		summarizeBy: sum
		sourceColumn: Base_Installment_AdminFee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Upgrade_Installment_Commission
		dataType: double
		lineageTag: b3793d09-3ca8-43fd-9c82-f81164daa997
		summarizeBy: sum
		sourceColumn: Upgrade_Installment_Commission

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Upgrade_Installment_AdminFee
		dataType: double
		lineageTag: d1dfc10f-6ee4-4255-a177-a1278763cbff
		summarizeBy: sum
		sourceColumn: Upgrade_Installment_AdminFee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column payment_month_num_v2 = ```
			
			IF(
			    AND(
			        ISBLANK(Fact_Trailer_bdx[PayDate]),
			        Fact_Trailer_bdx[type] = "Upgrade"
			    ),
			    YEAR(Fact_Trailer_bdx[cancelled_date]) * 100 + MONTH(Fact_Trailer_bdx[cancelled_date]),
			    Fact_Trailer_bdx[payment_month_num]
			)
			
			```
		formatString: 0
		lineageTag: a9d5baac-7b63-478d-9c99-a3f59c4ea8af
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PayDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: ac8fe34b-2a06-44b4-afda-1c95dbb0b858
		summarizeBy: none
		sourceColumn: PayDate

		variation Variation
			isDefault
			relationship: 88af013d-d54b-45fe-b4e0-447e607d4fdc
			defaultHierarchy: LocalDateTable_3a6caf07-0211-4a30-876a-64ccc0fb3cd2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column id
		dataType: int64
		formatString: 0
		lineageTag: 1c6a7ae2-d757-437e-9d7a-e0fe0e940347
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column CancellationEffectiveDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 01423998-b588-47d4-9f6d-b63dbd36ac4f
		summarizeBy: none
		sourceColumn: CancellationEffectiveDate

		variation Variation
			isDefault
			relationship: a476f23e-48c1-4308-a5b0-050af2cfc543
			defaultHierarchy: LocalDateTable_38e4f693-e4cb-4778-99c3-64ff854b329c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_Trailer_bdx = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				    Source = Fact_Trailer_bdx_base,
				
				    // Step 1: Add interval month logic
				    AddIntervalMonths = Table.AddColumn(Source, "IntervalMonths", each 
				        if [interval] = "monthly" then 1 
				        else if [interval] = "quarterly" then 3 
				        else if [interval] = "annual" then 12 
				        else 1, Int64.Type),
				    AddAlignedStart = Table.AddColumn(
				    AddIntervalMonths,
				    "AlignedStart",
				    each
				    let
				        base       = [policy_start_date],
				        eff        = [Effective_Date],
				        m          = [IntervalMonths],        // 1, 3, or 12
				        policyEnd  = [policy_end_date],
				
				        // helpers
				        MonthsBetween = (a as date, b as date) as number =>
				            (Date.Year(b) - Date.Year(a)) * 12 + (Date.Month(b) - Date.Month(a)),
				
				        // month-only alignment
				        startM     = Date.StartOfMonth(base),
				        effM       = Date.StartOfMonth(eff),
				        rem        = Number.Mod(MonthsBetween(startM, effM), m),
				        isAlignedMonth = (rem = 0),
				
				        // original schedule on the policy-start day (Date.AddMonths auto-clamps day)
				        originalSchedule =
				            List.Generate(
				                () => base,
				                (d) => d <= policyEnd,
				                (d) => Date.AddMonths(d, m)
				            ),
				
				        // first schedule date on/after Effective_Date
				        futurePayments = List.Select(originalSchedule, each _ >= eff),
				        nextPayment    = if List.Count(futurePayments) = 0 then null else List.First(futurePayments),
				
				        // RULE:
				        // - if effective month is aligned -> keep Effective_Date (keep its day)
				        // - else -> next aligned schedule date (policy-start day-of-month)
				        aligned =
				            if isAlignedMonth then
				                eff
				            else if nextPayment = null then
				                eff
				            else
				                nextPayment
				    in
				        if [type] = "Upgrade" then aligned else eff,
				    type date
				),
				    AddPayStart = Table.AddColumn(AddAlignedStart, "PayStart", each 
				        if [type] = "Upgrade" then [AlignedStart] else [Effective_Date]
				    ),
				
				    // Step 4: Generate PayDates
				    AddPayList = Table.AddColumn(AddPayStart, "PayList", each 
				        List.Generate(
				            () => [PayStart],
				            (d) => d <= [policy_end_date],
				            (d) => Date.AddMonths(d, [IntervalMonths])
				        )
				    ),
				    Expanded = Table.ExpandListColumn(AddPayList, "PayList"),
				    #"Renamed PayList To PayDate" = Table.RenameColumns(Expanded, {{"PayList", "PayDate"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed PayList To PayDate", "PayDate_temp", each if [PayDate] = null then [Effective_Date] else [PayDate]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"PayDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"PayDate_temp", "PayDate"}}),
				    // Step 5: Add Month IDs
				    AddPayMonth = Table.AddColumn(#"Renamed Columns", "payment_month_num", each Date.Year([PayDate]) * 100 + Date.Month([PayDate]), Int64.Type),
				    AddUWMonth = Table.AddColumn(AddPayMonth, "underwritten_month_num", each Date.Year([policy_start_date]) * 100 + Date.Month([policy_start_date]), Int64.Type),
				
				    // Step 6: Add CancellationEffectiveDate per reference
				    CancelRows = Table.SelectRows(Source, each [type] = "Cancelled"),
				    CancelEffective = Table.SelectColumns(CancelRows, {"id","reference", "Effective_Date"}),
				    RenameCancel = Table.RenameColumns(CancelEffective, {{"Effective_Date", "CancellationEffectiveDate"}}),
				    JoinCancel = Table.NestedJoin(AddUWMonth, "reference", RenameCancel, "reference", "CancelTable", JoinKind.LeftOuter),
				    ExpandCancel = Table.ExpandTableColumn(JoinCancel, "CancelTable", {"CancellationEffectiveDate"}),
				
				    // Step 7: Flag cancellation status
				    AddCancelFlag = Table.AddColumn(ExpandCancel, "CancellationStatus", each 
				    let
				        renewalDate = Date.AddYears([policy_start_date], 1),
				        renewalMonthNum = Date.Year(renewalDate) * 100 + Date.Month(renewalDate),
				        cancelMonthNum = Date.Year([CancellationEffectiveDate]) * 100 + Date.Month([CancellationEffectiveDate])
				    in
				        if [type] = "Cancelled" and cancelMonthNum >= renewalMonthNum then
				            "Renewal Cancellation"
				        else if [CancellationEffectiveDate] = null then 
				            "No Cancellation"
				        else if Date.Year([PayDate]) = Date.Year([CancellationEffectiveDate]) and Date.Month([PayDate]) = Date.Month([CancellationEffectiveDate]) then 
				            "In Cancellation Month"
				        else if [PayDate] > [CancellationEffectiveDate] then 
				            "After Cancellation"
				        else 
				            "Before Cancellation"
				),
				    // Step 8: Calculate instalment count
				    GroupInstCount = Table.Group(
				    AddCancelFlag,
				    {"id", "Effective_Date", "reference", "interval", "type"},
				    {
				        {"InstalmentCount", each 
				            let
				                t        = try [type]{0} otherwise null,
				                intvRaw  = try [interval]{0} otherwise null,
				                intv     = if intvRaw = null then null else Text.Lower(Text.Trim(intvRaw)),
				                count =
				                    if t = "Cancelled" then
				                        1
				                    else if intv = "monthly" then
				                        12
				                    else if intv = "quarterly" then
				                        4
				                    else if intv = "annual" then
				                        1
				                    else
				                        null  // unknown interval → return null (adjust if you want a default)
				            in
				                count,
				            Int64.Type}
				    }
				),
				    JoinInst = Table.NestedJoin(AddCancelFlag, {"reference", "type"}, GroupInstCount, {"reference", "type"}, "InstTbl", JoinKind.LeftOuter),
				    ExpandInst = Table.ExpandTableColumn(JoinInst, "InstTbl", {"InstalmentCount"}),
				
				    // Step 9: Base Premium/IPT/Admin/Commission per instalment
				    AddPrem = Table.AddColumn(ExpandInst, "Base_Installment_Premium", each 
				        if [type] = "Upgrade" or [InstalmentCount] = null or [InstalmentCount] = 0 or [annual_net_premium] = null then null 
				        else [annual_net_premium] / [InstalmentCount]),
				    AddIPT = Table.AddColumn(AddPrem, "Base_Installment_IPT", each 
				        if [type] = "Upgrade" or [InstalmentCount] = null or [InstalmentCount] = 0 or [ipt] = null then null 
				        else [ipt] / [InstalmentCount]),
				    AddCommission = Table.AddColumn(AddIPT, "Base_Installment_Commission", each 
				        if [type] = "Upgrade" or [InstalmentCount] = null or [InstalmentCount] = 0 or [annual_commision] = null then null 
				        else [annual_commision] / [InstalmentCount]),
				    AddAdminFee = Table.AddColumn(AddCommission, "Base_Installment_AdminFee", each 
				        if [type] = "Upgrade" or [InstalmentCount] = null or [InstalmentCount] = 0 or [admin_fee] = null then null 
				        else [admin_fee] / [InstalmentCount]),
				
				    // Step 10: Upgrade-specific logic — count aligned months from AlignedStart to policy_end_date
				    UpgradeRows = Table.SelectRows(AddCancelFlag, each [type] = "Upgrade"),
				    GroupUpgradeCount = Table.Group(
				    UpgradeRows,
				    {"id", "reference", "Effective_Date", "policy_start_date", "interval", "AlignedStart"},
				    {
				        {"upgrade_instalment_count", each 
				            let
				                firstRow   = Table.FirstN(_, 1){0},
				                eff        = firstRow[Effective_Date],
				                polStart   = firstRow[policy_start_date],
				                polEnd     = firstRow[policy_end_date],
				                interval   = firstRow[IntervalMonths],      // 1, 3, or 12
				
				                result =
				                    if eff = null or polStart = null or polEnd = null or interval = null then
				                        null
				                    else
				                        let
				                            // normalize to month starts
				                            effM     = Date.StartOfMonth(eff),
				                            startM   = Date.StartOfMonth(polStart),
				                            endM     = Date.StartOfMonth(polEnd),
				
				                            // months between two month-starts
				                            MonthsBetween = (a as date, b as date) as number =>
				                                (Date.Year(b) - Date.Year(a)) * 12 + (Date.Month(b) - Date.Month(a)),
				
				                            // how far effM is into the cycle
				                            mDiff    = MonthsBetween(startM, effM),
				                            rem      = Number.Mod(mDiff, interval),
				
				                            // round UP to the next aligned month on/after effM (month-only logic)
				                            addToAlign    = Number.Mod(interval - rem, interval),
				                            firstAlignedM = Date.AddMonths(effM, addToAlign),
				
				                            // if first aligned month is beyond policy end, still return 1 (your rule)
				                            rawCount =
				                                if firstAlignedM > endM then
				                                    1
				                                else
				                                    Number.IntegerDivide(MonthsBetween(firstAlignedM, endM), interval) + 1,
				
				                            final = if rawCount < 1 then 1 else rawCount
				                        in
				                            if interval = 12 then 1 else final
				            in
				                result,
				            Int64.Type}
				    }
				),
				    JoinUpgradeCount = Table.NestedJoin(AddAdminFee, {"reference", "Effective_Date"}, GroupUpgradeCount, {"reference", "Effective_Date"}, "UpgradeCount", JoinKind.LeftOuter),
				    ExpandUpgrade = Table.ExpandTableColumn(JoinUpgradeCount, "UpgradeCount", {"upgrade_instalment_count"}),
				    // Step 11: Upgrade Premium/IPT/Admin/Commission per aligned month (null-safe)
				    AddUpgradePrem = Table.AddColumn(ExpandUpgrade, "Upgrade_Installment_Premium", each 
				        if [type] = "Upgrade" 
				            and [upgrade_instalment_count] <> null 
				            and [upgrade_instalment_count] > 0 
				            and [annual_net_premium] <> null then 
				            [annual_net_premium] / [upgrade_instalment_count] 
				        else null),
				    AddUpgradeIPT = Table.AddColumn(AddUpgradePrem, "Upgrade_Installment_IPT", each 
				        if [type] = "Upgrade" 
				            and [upgrade_instalment_count] <> null 
				            and [upgrade_instalment_count] > 0 
				            and [ipt] <> null then 
				            [ipt] / [upgrade_instalment_count] 
				        else null),
				    AddUpgradeCommission = Table.AddColumn(AddUpgradeIPT, "Upgrade_Installment_Commission", each 
				        if [type] = "Upgrade" 
				            and [upgrade_instalment_count] <> null 
				            and [upgrade_instalment_count] > 0 
				            and [annual_commision] <> null then 
				            [annual_commision] / [upgrade_instalment_count] 
				        else null),
				    AddUpgradeAdminFee = Table.AddColumn(AddUpgradeCommission, "Upgrade_Installment_AdminFee", each 
				        if [type] = "Upgrade" 
				            and [upgrade_instalment_count] <> null 
				            and [upgrade_instalment_count] > 0 
				            and [admin_fee] <> null then 
				            [admin_fee] / [upgrade_instalment_count] 
				        else null),
				
				    // Final formatting
				    #"Changed Type" = Table.TransformColumnTypes(AddUpgradeAdminFee, {
				        {"policy_start_date", type date}, {"reference", type text}, {"cancelled_date", type date}, {"days_used", Int64.Type}, {"days_paid", Int64.Type}, {"interval", type text}, {"type", type text}, 
				        {"annual_cost", type number}, {"annual_premium_excl_ipt", type number}, {"annual_net_premium", type number}, {"ipt", type number}, {"annual_commision", type number}, {"admin_fee", type number}, 
				        {"Effective_Date", type date}, {"policy_end_date", type date}, {"IntervalMonths", Int64.Type}, {"AlignedStart", type date}, {"PayStart", type date}, {"PayDate", type date}, 
				        {"payment_month_num", Int64.Type}, {"underwritten_month_num", Int64.Type}, {"CancellationEffectiveDate", type date}, {"CancellationStatus", type text}, 
				        {"InstalmentCount", Int64.Type}, 
				        {"Base_Installment_Premium", type number}, {"Base_Installment_IPT", type number}, {"Base_Installment_Commission", type number}, {"Base_Installment_AdminFee", type number}, 
				        {"upgrade_instalment_count", type number}, 
				        {"Upgrade_Installment_Premium", type number}, {"Upgrade_Installment_IPT", type number}, {"Upgrade_Installment_Commission", type number}, {"Upgrade_Installment_AdminFee", type number}
				    }),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "CancellationEffectiveDate_YearMonthNum", each Date.Year([CancellationEffectiveDate]) * 100 + Date.Month([CancellationEffectiveDate]), Int64.Type),
				    #"Removed Duplicates" = Table.Distinct(#"Added Custom")
				in
				    #"Removed Duplicates"
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

