table Fact_Vet_bdx
	lineageTag: 4b8d4e0f-f9cf-4a10-856f-39064470bfe0

	column policy_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc74795f-0cfe-40be-8e38-28e050cf2e0a
		summarizeBy: none
		sourceColumn: policy_start_date

		variation Variation
			isDefault
			relationship: 3f8e9b94-0a49-4a11-9c75-c55b7109f0af
			defaultHierarchy: LocalDateTable_33bbd491-ac1b-44b0-8f92-5154ae3dd17f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reference
		dataType: string
		lineageTag: 6e5a098d-33ff-4b73-bc26-8e569b6cefcd
		summarizeBy: none
		sourceColumn: reference

		annotation SummarizationSetBy = Automatic

	column cancelled_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a450986b-2b40-4cdc-b57f-4f842dfa41fa
		summarizeBy: none
		sourceColumn: cancelled_date

		variation Variation
			isDefault
			relationship: 77d8e8f3-5a37-4f36-9fc9-79c2f29b627e
			defaultHierarchy: LocalDateTable_5a373502-537d-418f-b445-07a89f1b1404.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column interval
		dataType: string
		lineageTag: d8638695-bd52-4de8-a435-a45e705666b3
		summarizeBy: none
		sourceColumn: interval

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 99d4e7ea-c390-4e5d-ad43-29aa06da10db
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column days_used
		dataType: int64
		formatString: 0
		lineageTag: 8c8a92b1-377c-4187-a345-40291ace2d54
		summarizeBy: sum
		sourceColumn: days_used

		annotation SummarizationSetBy = Automatic

	column days_paid
		dataType: int64
		formatString: 0
		lineageTag: 66795049-d0fe-4269-a58a-34b9c0dae50f
		summarizeBy: sum
		sourceColumn: days_paid

		annotation SummarizationSetBy = Automatic

	column annual_cost
		dataType: double
		lineageTag: 8390586d-e4d2-4e34-a42a-17420d1ba411
		summarizeBy: sum
		sourceColumn: annual_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column annual_vet_premium_excl_ipt
		dataType: double
		lineageTag: de7a2c98-308d-4f27-9fae-2d9fcf282bae
		summarizeBy: sum
		sourceColumn: annual_vet_premium_excl_ipt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column annual_vet_premium_incl_ipt_commision
		dataType: double
		lineageTag: 9c1a0382-bed7-4fe2-b73b-da11e6d51413
		summarizeBy: sum
		sourceColumn: annual_vet_premium_incl_ipt_commision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column annual_vet_net_premium
		dataType: double
		lineageTag: 86fe4855-c14d-475a-bd61-9da26ad77f48
		summarizeBy: sum
		sourceColumn: annual_vet_net_premium

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ipt
		dataType: double
		lineageTag: 531f02f5-8564-4470-8375-1ab681b1e5bc
		summarizeBy: sum
		sourceColumn: ipt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column annual_vet_commission
		dataType: double
		lineageTag: e161e0c8-c98a-45de-b94c-383e45b02153
		summarizeBy: sum
		sourceColumn: annual_vet_commission

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column admin_fee
		dataType: double
		lineageTag: 9fba3baf-c4ac-4b0e-bcbc-c5ce5632bbc5
		summarizeBy: sum
		sourceColumn: admin_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Effective_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e8579f2b-7df9-4f1e-909d-109b19ccc636
		summarizeBy: none
		sourceColumn: Effective_Date

		variation Variation
			isDefault
			relationship: 8a977d70-c576-473a-aabc-971f0748dafb
			defaultHierarchy: LocalDateTable_8af8dd7a-6d7c-418b-8775-f9446684955a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column policy_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 975ee606-fc70-4b00-ac6a-3b5cb3eb0f39
		summarizeBy: none
		sourceColumn: policy_end_date

		variation Variation
			isDefault
			relationship: 641a38d7-ee29-4f0d-89d7-1f4e2d17e4a3
			defaultHierarchy: LocalDateTable_eefdb81b-92df-41cc-813c-d719ed78c6e4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IntervalMonths
		dataType: int64
		formatString: 0
		lineageTag: b6770520-e02f-404d-aee3-38ca098afa1c
		summarizeBy: sum
		sourceColumn: IntervalMonths

		annotation SummarizationSetBy = Automatic

	column AlignedStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8c196922-c38f-4563-b8b4-79fa7c97d198
		summarizeBy: none
		sourceColumn: AlignedStart

		variation Variation
			isDefault
			relationship: 449d2e6c-6659-4c58-a322-7c1899883626
			defaultHierarchy: LocalDateTable_01aa78b9-4c75-416f-8b87-35d09ba6610c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PayStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: b5a154c3-14ed-4b4a-b994-d714752b75b1
		summarizeBy: none
		sourceColumn: PayStart

		variation Variation
			isDefault
			relationship: 6f432119-894b-4d3c-8393-98f74e74395c
			defaultHierarchy: LocalDateTable_a1ccb5e5-6b3f-485a-b786-c47329854c94.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PayDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 944d6d12-1bc9-4c5a-ac5e-4321e8ef65ce
		summarizeBy: none
		sourceColumn: PayDate

		variation Variation
			isDefault
			relationship: b8637770-5d20-4ae5-880e-f38b29206f5f
			defaultHierarchy: LocalDateTable_ad94cb93-e3d5-4258-a356-28fab483a9f4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column payment_month_num
		dataType: int64
		formatString: 0
		lineageTag: 26644d4b-cf61-4ae1-93a3-ab778c4cb6e7
		summarizeBy: none
		sourceColumn: payment_month_num

		annotation SummarizationSetBy = Automatic

	column underwritten_month_num
		dataType: int64
		formatString: 0
		lineageTag: 3648c31e-f069-47e1-b05a-550b21490b9a
		summarizeBy: none
		sourceColumn: underwritten_month_num

		annotation SummarizationSetBy = Automatic

	column CancellationStatus
		dataType: string
		lineageTag: 7e95daf3-002f-479b-8626-07b09b551dbc
		summarizeBy: none
		sourceColumn: CancellationStatus

		annotation SummarizationSetBy = Automatic

	column InstalmentCount
		dataType: int64
		formatString: 0
		lineageTag: e49d3894-e285-42ab-9712-afef3939496d
		summarizeBy: sum
		sourceColumn: InstalmentCount

		annotation SummarizationSetBy = Automatic

	column Base_Installment_Premium
		dataType: double
		lineageTag: d5b84ca2-86a3-4135-9d56-fe90a0fb80b3
		summarizeBy: sum
		sourceColumn: Base_Installment_Premium

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Base_Installment_IPT
		dataType: double
		lineageTag: 4dfbd4cd-a12e-4f03-9f99-b753d07ad658
		summarizeBy: sum
		sourceColumn: Base_Installment_IPT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CancellationEffectiveDate_YearMonthNum
		dataType: int64
		formatString: 0
		lineageTag: ca25ecaf-6efa-4303-ae86-70e85645629d
		summarizeBy: sum
		sourceColumn: CancellationEffectiveDate_YearMonthNum

		annotation SummarizationSetBy = Automatic

	column Base_Installment_Commission
		dataType: double
		lineageTag: e26c0d53-5f28-4650-b47f-b32b44d4008b
		summarizeBy: sum
		sourceColumn: Base_Installment_Commission

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column upgrade_instalment_count
		dataType: int64
		formatString: 0
		lineageTag: 052ab8c1-be75-4579-bc40-21f42f66cd43
		summarizeBy: sum
		sourceColumn: upgrade_instalment_count

		annotation SummarizationSetBy = Automatic

	column Upgrade_Installment_Premium
		dataType: double
		lineageTag: 0dd6c5e3-6736-482e-aa07-a96fbc6c4470
		summarizeBy: sum
		sourceColumn: Upgrade_Installment_Premium

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Upgrade_Installment_IPT
		dataType: double
		lineageTag: 99deab62-0b51-418c-a514-530fe31b8cf2
		summarizeBy: sum
		sourceColumn: Upgrade_Installment_IPT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Upgrade_Installment_Commission
		dataType: double
		lineageTag: fc234a9c-c342-4bb2-abe4-45b60d904a43
		summarizeBy: sum
		sourceColumn: Upgrade_Installment_Commission

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Base_Installment_AdminFee
		dataType: double
		lineageTag: 1958a494-bba4-4b85-8de4-50d2382bd091
		summarizeBy: sum
		sourceColumn: Base_Installment_AdminFee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Upgrade_Installment_AdminFee
		dataType: double
		lineageTag: de276583-6708-4568-8f84-2ab9af8255b4
		summarizeBy: sum
		sourceColumn: Upgrade_Installment_AdminFee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column id
		dataType: int64
		formatString: 0
		lineageTag: 060881ad-acd4-4f5b-93f0-4a1e4d369527
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column CancellationEffectiveDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6a6dae25-1431-4785-ba15-510075f0f590
		summarizeBy: none
		sourceColumn: CancellationEffectiveDate

		variation Variation
			isDefault
			relationship: 6c67560f-8c2e-4cfb-aae9-3f8e614a0edb
			defaultHierarchy: LocalDateTable_7aa1e76c-88ca-4c05-8900-f132b580d596.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_Vet_bdx = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				    Source = Fact_Vet_bbx_base,
				
				    // Step 1: Add interval month logic
				    AddIntervalMonths = Table.AddColumn(Source, "IntervalMonths", each 
				        if [interval] = "monthly" then 1 
				        else if [interval] = "quarterly" then 3 
				        else if [interval] = "annual" then 12 
				        else 1, Int64.Type),
				
				    // Step 2: Aligned start (for upgrade payment alignment)
				    AddAlignedStart = Table.AddColumn(AddIntervalMonths, "AlignedStart", each 
				        let
				            base = [policy_start_date],
				            eff = [Effective_Date],
				            m = [IntervalMonths],
				            offset = Number.RoundUp(Duration.Days(eff - base) / 30),
				            aligned = Number.RoundUp(offset / m) * m
				        in
				            Date.AddMonths(base, aligned)
				    ),
				
				    // Step 3: Set payment start date (aligned for upgrades)
				    AddPayStart = Table.AddColumn(AddAlignedStart, "PayStart", each 
				        if [type] = "Upgrade" then [AlignedStart] else [Effective_Date]
				    ),
				
				    // Step 4: Generate PayDates
				    AddPayList = Table.AddColumn(AddPayStart, "PayList", each 
				        List.Generate(
				            () => [PayStart],
				            (d) => d <= [policy_end_date],
				            (d) => Date.AddMonths(d, [IntervalMonths])
				        )
				    ),
				    Expanded = Table.ExpandListColumn(AddPayList, "PayList"),
				    Renamed = Table.RenameColumns(Expanded, {{"PayList", "PayDate"}}),
				
				    // Step 5: Add Month IDs
				    AddPayMonth = Table.AddColumn(Renamed, "payment_month_num", each Date.Year([PayDate]) * 100 + Date.Month([PayDate]), Int64.Type),
				    AddUWMonth = Table.AddColumn(AddPayMonth, "underwritten_month_num", each Date.Year([policy_start_date]) * 100 + Date.Month([policy_start_date]), Int64.Type),
				
				    // Step 6: Add CancellationEffectiveDate per reference
				    CancelRows = Table.SelectRows(Source, each [type] = "Cancelled"),
				    CancelEffective = Table.SelectColumns(CancelRows, {"id","reference", "Effective_Date"}),
				    RenameCancel = Table.RenameColumns(CancelEffective, {{"Effective_Date", "CancellationEffectiveDate"}}),
				    JoinCancel = Table.NestedJoin(AddUWMonth, "reference", RenameCancel, "reference", "CancelTable", JoinKind.LeftOuter),
				    ExpandCancel = Table.ExpandTableColumn(JoinCancel, "CancelTable", {"CancellationEffectiveDate"}),
				
				    // Step 7: Flag cancellation status
				    AddCancelFlag = Table.AddColumn(ExpandCancel, "CancellationStatus", each 
				    let
				        renewalDate = Date.AddYears([policy_start_date], 1),
				        renewalMonthNum = Date.Year(renewalDate) * 100 + Date.Month(renewalDate),
				        cancelMonthNum = Date.Year([CancellationEffectiveDate]) * 100 + Date.Month([CancellationEffectiveDate])
				    in
				        if [type] = "Cancelled" and cancelMonthNum >= renewalMonthNum then
				            "Renewal Cancellation"
				        else if [CancellationEffectiveDate] = null then 
				            "No Cancellation"
				        else if Date.Year([PayDate]) = Date.Year([CancellationEffectiveDate]) and Date.Month([PayDate]) = Date.Month([CancellationEffectiveDate]) then 
				            "In Cancellation Month"
				        else if [PayDate] > [CancellationEffectiveDate] then 
				            "After Cancellation"
				        else 
				            "Before Cancellation"
				),
				    // Step 8: Calculate instalment count
				    GroupInstCount = Table.Group(
				    AddCancelFlag,
				    {"id", "Effective_Date", "reference", "interval", "type"},
				    {
				        {"InstalmentCount", each 
				            let
				                t        = try [type]{0} otherwise null,
				                intvRaw  = try [interval]{0} otherwise null,
				                intv     = if intvRaw = null then null else Text.Lower(Text.Trim(intvRaw)),
				                count =
				                    if t = "Cancelled" then
				                        1
				                    else if intv = "monthly" then
				                        12
				                    else if intv = "quarterly" then
				                        4
				                    else if intv = "annual" then
				                        1
				                    else
				                        null  // unknown interval → return null (adjust if you want a default)
				            in
				                count,
				            Int64.Type}
				    }
				),
				    JoinInst = Table.NestedJoin(AddCancelFlag, {"reference", "type"}, GroupInstCount, {"reference", "type"}, "InstTbl", JoinKind.LeftOuter),
				    ExpandInst = Table.ExpandTableColumn(JoinInst, "InstTbl", {"InstalmentCount"}),
				
				    // Step 8.5: Base Instalments (Premium, IPT, Commission, Admin Fee)
				    AddPrem = Table.AddColumn(ExpandInst, "Base_Installment_Premium", each 
				        if [type] = "Upgrade" or [InstalmentCount] = null or [InstalmentCount] = 0 or [annual_vet_net_premium] = null then null 
				        else [annual_vet_net_premium] / [InstalmentCount], type number),
				    AddIPT = Table.AddColumn(AddPrem, "Base_Installment_IPT", each 
				        if [type] = "Upgrade" or [InstalmentCount] = null or [InstalmentCount] = 0 or [ipt] = null then null 
				        else [ipt] / [InstalmentCount], type number),
				    AddCommission = Table.AddColumn(AddIPT, "Base_Installment_Commission", each 
				        if [type] = "Upgrade" or [InstalmentCount] = null or [InstalmentCount] = 0 or [annual_vet_commission] = null then null 
				        else [annual_vet_commission] / [InstalmentCount], type number),
				    AddAdminFee = Table.AddColumn(AddCommission, "Base_Installment_AdminFee", each 
				        if [type] = "Upgrade" or [InstalmentCount] = null or [InstalmentCount] = 0 or [admin_fee] = null then null 
				        else [admin_fee] / [InstalmentCount], type number),
				
				    // Step 9: Upgrade Instalment Count
				    UpgradeRows = Table.SelectRows(AddCancelFlag, each [type] = "Upgrade"),
				    GroupUpgradeCount = Table.Group(
				        UpgradeRows,
				        {"reference", "Effective_Date", "policy_start_date", "interval", "AlignedStart"},
				        {
				            {"upgrade_instalment_count", each 
				                let
				                    firstRow = Table.FirstN(_, 1){0},
				                    aligned = firstRow[AlignedStart],
				                    policyEnd = firstRow[policy_end_date],
				                    interval = firstRow[IntervalMonths],
				                    count = if interval = 12 then 1
				                            else List.Count(
				                                List.Generate(
				                                    () => aligned,
				                                    (d) => d <= policyEnd,
				                                    (d) => Date.AddMonths(d, interval)
				                                )
				                            )
				                in count, Int64.Type}
				        }
				    ),
				    JoinUpgradeCount = Table.NestedJoin(AddAdminFee, {"reference", "Effective_Date"}, GroupUpgradeCount, {"reference", "Effective_Date"}, "UpgradeCount", JoinKind.LeftOuter),
				    ExpandUpgrade = Table.ExpandTableColumn(JoinUpgradeCount, "UpgradeCount", {"upgrade_instalment_count"}),
				
				    // Step 10: Upgrade Instalments (Premium, IPT, Commission, Admin Fee)
				    AddUpgradePrem = Table.AddColumn(ExpandUpgrade, "Upgrade_Installment_Premium", each 
				        if [type] = "Upgrade" 
				            and [upgrade_instalment_count] <> null 
				            and [upgrade_instalment_count] > 0 
				            and [annual_vet_net_premium] <> null then 
				            [annual_vet_net_premium] / [upgrade_instalment_count] 
				        else null, type number),
				    AddUpgradeIPT = Table.AddColumn(AddUpgradePrem, "Upgrade_Installment_IPT", each 
				        if [type] = "Upgrade" 
				            and [upgrade_instalment_count] <> null 
				            and [upgrade_instalment_count] > 0 
				            and [ipt] <> null then 
				            [ipt] / [upgrade_instalment_count] 
				        else null, type number),
				    AddUpgradeCommission = Table.AddColumn(AddUpgradeIPT, "Upgrade_Installment_Commission", each 
				        if [type] = "Upgrade" 
				            and [upgrade_instalment_count] <> null 
				            and [upgrade_instalment_count] > 0 
				            and [annual_vet_commission] <> null then 
				            [annual_vet_commission] / [upgrade_instalment_count] 
				        else null, type number),
				    AddUpgradeAdminFee = Table.AddColumn(AddUpgradeCommission, "Upgrade_Installment_AdminFee", each 
				        if [type] = "Upgrade" 
				            and [upgrade_instalment_count] <> null 
				            and [upgrade_instalment_count] > 0 
				            and [admin_fee] <> null then 
				            [admin_fee] / [upgrade_instalment_count] 
				        else null, type number),
				
				    // Final formatting
				    #"Changed Type" = Table.TransformColumnTypes(AddUpgradeAdminFee, {
				        {"policy_start_date", type date}, {"reference", type text}, {"cancelled_date", type date},
				        {"days_used", Int64.Type}, {"days_paid", Int64.Type}, {"interval", type text}, {"type", type text},
				        {"annual_cost", type number}, {"annual_vet_net_premium", type number}, {"ipt", type number}, 
				        {"annual_vet_commission", type number}, {"admin_fee", type number},
				        {"Effective_Date", type date}, {"policy_end_date", type date}, {"IntervalMonths", Int64.Type},
				        {"AlignedStart", type date}, {"PayStart", type date}, {"PayDate", type date}, 
				        {"payment_month_num", Int64.Type}, {"underwritten_month_num", Int64.Type}, 
				        {"CancellationEffectiveDate", type date}, {"CancellationStatus", type text},
				        {"InstalmentCount", Int64.Type}, 
				        {"Base_Installment_Premium", type number}, {"Base_Installment_IPT", type number}, {"Base_Installment_Commission", type number}, {"Base_Installment_AdminFee", type number},
				        {"upgrade_instalment_count", Int64.Type}, 
				        {"Upgrade_Installment_Premium", type number}, {"Upgrade_Installment_IPT", type number}, {"Upgrade_Installment_Commission", type number}, {"Upgrade_Installment_AdminFee", type number}
				    }),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "CancellationEffectiveDate_YearMonthNum", each Date.Year([CancellationEffectiveDate]) * 100 + Date.Month([CancellationEffectiveDate]), Int64.Type)
				in
				    #"Added Custom"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

