table pa_table_EOMonth
	lineageTag: e375aff2-466f-4d29-aa78-183b446dbf49

	column 'Date modified'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7b60f6ac-7751-4697-99b0-63d4e7be65e4
		summarizeBy: none
		sourceColumn: Date modified

		variation Variation
			isDefault
			relationship: 7193a216-6e80-4712-aadf-a66f9b2fd547
			defaultHierarchy: LocalDateTable_3108a6f0-0539-406f-9334-d6c4a7a1342f.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column [IsGrandTotalRowTotal]
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 11e9b174-d510-4125-817a-821c2536e5b0
		summarizeBy: none
		sourceColumn: [IsGrandTotalRowTotal]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column [pa_payment_total]
		dataType: double
		lineageTag: c181199f-c823-453d-8890-5cff40601b9a
		summarizeBy: sum
		sourceColumn: [pa_payment_total]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column [ipt_pa_payment_total]
		dataType: double
		lineageTag: a70aa581-067f-43e0-a793-b6396df88175
		summarizeBy: sum
		sourceColumn: [ipt_pa_payment_total]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column [commission_pa_payment_total]
		dataType: double
		lineageTag: 116805f8-8c66-43b9-831f-00e780b56491
		summarizeBy: sum
		sourceColumn: [commission_pa_payment_total]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column [admin_fee_pa_pl_payment_total]
		dataType: double
		lineageTag: 22d49aa1-4b3e-420e-a76e-10cb6a46a532
		summarizeBy: sum
		sourceColumn: [admin_fee_pa_pl_payment_total]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dim_UWDate[MonthYearShort]
		dataType: string
		lineageTag: fb18c9a5-6dd6-4133-b428-f21b3926a25b
		summarizeBy: none
		sourceColumn: dim_UWDate[MonthYearShort]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dim_UWDate[MonthYearNum]
		dataType: int64
		formatString: 0
		lineageTag: ccdd9ff0-ff71-416c-84d8-c119a7fbc326
		summarizeBy: none
		sourceColumn: dim_UWDate[MonthYearNum]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dim_BDXDate[MonthYearShort]
		dataType: string
		lineageTag: e7f85bb7-2bf0-4697-982a-0c7995295258
		summarizeBy: none
		sourceColumn: dim_BDXDate[MonthYearShort]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dim_BDXDate[MonthYearNum]
		dataType: int64
		formatString: 0
		lineageTag: 780cc8bd-29bf-454c-a384-17fc7a169ab0
		summarizeBy: none
		sourceColumn: dim_BDXDate[MonthYearNum]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d3b163a7-3b39-4bdd-a978-f03100ed6ad2
		summarizeBy: none
		sourceColumn: MonthName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: 0585f5fc-06e1-42f9-a761-5094191ec47d
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition pa_table_EOMonth = m
		mode: import
		queryGroup: 'End Of Month'
		source =
				let
				    Source = #"SharePoint Connection",
				    #"Filtered To Personal Accident" = Table.SelectRows(Source, each [Folder Path] = "https://harryh.sharepoint.com/sites/HarryHallFullTeam/Shared Documents/Power BI/2. Personal Accident/"),
				    #"Kept csv. files only" = Table.SelectRows(#"Filtered To Personal Accident", each [Extension] = ".csv"),
				    #"Sorted Date modified descending" = Table.Sort(#"Kept csv. files only",{{"Date modified", Order.Descending}}),
				    #"Kept last modified row" = Table.FirstN(#"Sorted Date modified descending",1),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Kept last modified row", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Date modified", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"[IsGrandTotalRowTotal]", type logical}, {"[pa_payment_total]", type number}, {"[ipt_pa_payment_total]", type number}, {"[commission_pa_payment_total]", type number}, {"[admin_fee_pa_pl_payment_total]", type number}, {"dim_UWDate[MonthYearNum]", Int64.Type}, {"dim_BDXDate[MonthYearNum]", Int64.Type}, {"dim_UWDate[MonthYearShort]", type text}, {"dim_BDXDate[MonthYearShort]", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [#"[IsGrandTotalRowTotal]"] <> true),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Custom", each let
				    LastFile = Table.FirstN(#"Filtered Rows", 1),
				    FileDate = Record.Field(Table.First(LastFile), "Date modified"),
				    MonthMinus1 = Date.AddMonths(Date.From(FileDate), -1),
				    MonthName = Date.ToText(MonthMinus1, "MMMM"),
				    Year = Date.Year(MonthMinus1)
				in
				    [MonthName = MonthName, Year = Year]),
				    #"Expanded Custom" = Table.ExpandRecordColumn(#"Added Custom", "Custom", {"MonthName", "Year"}, {"MonthName", "Year"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded Custom",{{"MonthName", type text}, {"Year", type text}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

