table pl_table_EOMonth
	lineageTag: 4d31ac52-6b64-40f6-afe1-eb7f718b16d9

	column 'Date modified'
		dataType: dateTime
		formatString: General Date
		lineageTag: c668a673-90fa-443e-b5c9-be280ddbf040
		summarizeBy: none
		sourceColumn: Date modified

		variation Variation
			isDefault
			relationship: 00a5cbde-1e2c-4ab2-a7ee-b1decfdd8405
			defaultHierarchy: LocalDateTable_7c014445-9a2e-4360-9d9c-fc916b105d53.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column [IsGrandTotalRowTotal]
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7346a3b5-ba40-47c5-b9df-a65c9c5a928d
		summarizeBy: none
		sourceColumn: [IsGrandTotalRowTotal]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column [pl_payment_total]
		dataType: double
		lineageTag: 5dc4f819-ed8d-440e-9a18-79c02bf08578
		summarizeBy: sum
		sourceColumn: [pl_payment_total]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column [ipt_pl_payment_total]
		dataType: double
		lineageTag: ee2176e5-9a43-4677-aa7c-873591664642
		summarizeBy: sum
		sourceColumn: [ipt_pl_payment_total]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column [commission_pl_payment_total]
		dataType: double
		lineageTag: 3191316b-dfe9-4f04-aeb3-739e9e564982
		summarizeBy: sum
		sourceColumn: [commission_pl_payment_total]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column [admin_fee_pa_pl_payment_total]
		dataType: double
		lineageTag: 976f41db-3577-4fa5-af41-d49c41838e18
		summarizeBy: sum
		sourceColumn: [admin_fee_pa_pl_payment_total]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dim_UWDate[MonthYearShort]
		dataType: string
		lineageTag: 31c1802f-3e4f-40e6-8f88-1afd5e205126
		summarizeBy: none
		sourceColumn: dim_UWDate[MonthYearShort]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dim_UWDate[MonthYearNum]
		dataType: int64
		formatString: 0
		lineageTag: 35a3ea8f-7dcf-4652-8366-7c3789e08e00
		summarizeBy: none
		sourceColumn: dim_UWDate[MonthYearNum]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dim_BDXDate[MonthYearShort]
		dataType: string
		lineageTag: f1343918-d581-4a1e-9e4a-f2c201de41d5
		summarizeBy: none
		sourceColumn: dim_BDXDate[MonthYearShort]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dim_BDXDate[MonthYearNum]
		dataType: int64
		formatString: 0
		lineageTag: bab9d697-bfdb-4e24-892d-1e7bca1e6618
		summarizeBy: none
		sourceColumn: dim_BDXDate[MonthYearNum]

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 645ef0fd-bc97-4026-a590-246359eb40f3
		summarizeBy: none
		sourceColumn: MonthName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: 75aada8b-ac59-4e9e-85d9-67763694fd72
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition pl_table_EOMonth = m
		mode: import
		queryGroup: 'End Of Month'
		source =
				let
				    Source = #"SharePoint Connection",
				    #"Filtered to Public Liability" = Table.SelectRows(Source, each ([Folder Path] = "https://harryh.sharepoint.com/sites/HarryHallFullTeam/Shared Documents/Power BI/1. Public Liability/")),
				    #"Kept only .csv files" = Table.SelectRows(#"Filtered to Public Liability", each [Extension] = ".csv"),
				    #"Sorted Date modified descending" = Table.Sort(#"Kept only .csv files",{{"Date modified", Order.Descending}}),
				    #"Kept last modified row" = Table.FirstN(#"Sorted Date modified descending",1),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Kept last modified row", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Date modified", "Transform File (2)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"[IsGrandTotalRowTotal]", type logical}, {"[pl_payment_total]", type number}, {"[ipt_pl_payment_total]", type number}, {"[commission_pl_payment_total]", type number}, {"[admin_fee_pa_pl_payment_total]", type number}, {"dim_UWDate[MonthYearNum]", Int64.Type}, {"dim_BDXDate[MonthYearNum]", Int64.Type}, {"dim_UWDate[MonthYearShort]", type text}, {"dim_BDXDate[MonthYearShort]", type text}}),
				    #"Filtered out IsGrandTotalRow = True" = Table.SelectRows(#"Changed Type", each [#"[IsGrandTotalRowTotal]"] <> true),
				    #"Added Custom" = Table.AddColumn(#"Filtered out IsGrandTotalRow = True", "Custom", each let
				    LastFile = Table.FirstN(#"Filtered out IsGrandTotalRow = True", 1),
				    FileDate = Record.Field(Table.First(LastFile), "Date modified"),
				    MonthMinus1 = Date.AddMonths(Date.From(FileDate), -1),
				    MonthName = Date.ToText(MonthMinus1, "MMMM"),
				    Year = Date.Year(MonthMinus1)
				in
				    [MonthName = MonthName, Year = Year]),
				    #"Expanded Custom" = Table.ExpandRecordColumn(#"Added Custom", "Custom", {"MonthName", "Year"}, {"MonthName", "Year"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded Custom",{{"MonthName", type text}, {"Year", type text}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

