productA_comm_total =

VAR RegularComm =
    SUMX(
        FILTER(
            PaymentSchedule,
            PaymentSchedule[CancellationStatus] IN {
                "Before Cancellation",
                "No Cancellation"
            }
        ),
        PaymentSchedule[Base_Installment_Commission_ProductA] +
        PaymentSchedule[Upgrade_Installment_Commission_ProductA]
    )

VAR RemainingComm =
    CALCULATE(
        SUMX(
            FILTER(
                PaymentSchedule,
                PaymentSchedule[CancellationStatus] IN {
                    "After Cancellation",
                    "In Cancellation Month"
                }
                && PaymentSchedule[EventType] <> "Cancelled"
            ),
            PaymentSchedule[Base_Installment_Commission_ProductA] +
            PaymentSchedule[Upgrade_Installment_Commission_ProductA]
        ),
        USERELATIONSHIP(
            PaymentSchedule[CancellationEffectiveDate_YearMonthNum],
            dim_PymtDate[MonthYearNum]
        )
    )

VAR CancelledRowComm =
    CALCULATE(
        SUMX(
            FILTER(
                PaymentSchedule,
                PaymentSchedule[EventType] = "Cancelled"
                    && PaymentSchedule[CancellationStatus] IN {
                        "In Cancellation Month",
                        "Renewal Cancellation"
                    }
            ),
            PaymentSchedule[Base_Installment_Commission_ProductA] +
            PaymentSchedule[Upgrade_Installment_Commission_ProductA]
        ),
        USERELATIONSHIP(
            PaymentSchedule[CancellationEffectiveDate_YearMonthNum],
            dim_PymtDate[MonthYearNum]
        )
    )

VAR LumpSum = CancelledRowComm + RemainingComm

RETURN
    RegularComm + LumpSum
