productA_tax_total =

VAR RegularTax =
    SUMX(
        FILTER(
            PaymentSchedule,
            PaymentSchedule[CancellationStatus] IN {
                "Before Cancellation",
                "No Cancellation"
            }
        ),
        PaymentSchedule[Base_Installment_Tax_ProductA] +
        PaymentSchedule[Upgrade_Installment_Tax_ProductA]
    )

VAR RemainingTax =
    CALCULATE(
        SUMX(
            FILTER(
                PaymentSchedule,
                PaymentSchedule[CancellationStatus] IN {
                    "After Cancellation",
                    "In Cancellation Month"
                }
                && PaymentSchedule[EventType] <> "Cancelled"
            ),
            PaymentSchedule[Base_Installment_Tax_ProductA] +
            PaymentSchedule[Upgrade_Installment_Tax_ProductA]
        ),
        USERELATIONSHIP(
            PaymentSchedule[CancellationEffectiveDate_YearMonthNum],
            dim_PymtDate[MonthYearNum]
        )
    )

VAR CancelledRowTax =
    CALCULATE(
        SUMX(
            FILTER(
                PaymentSchedule,
                PaymentSchedule[EventType] = "Cancelled"
                    && PaymentSchedule[CancellationStatus] IN {
                        "In Cancellation Month",
                        "Renewal Cancellation"
                    }
            ),
            PaymentSchedule[Base_Installment_Tax_ProductA] +
            PaymentSchedule[Upgrade_Installment_Tax_ProductA]
        ),
        USERELATIONSHIP(
            PaymentSchedule[CancellationEffectiveDate_YearMonthNum],
            dim_PymtDate[MonthYearNum]
        )
    )

VAR LumpSum = CancelledRowTax + RemainingTax

RETURN
    RegularTax + LumpSum
