productA_payment_total =

VAR RegularPayments =
    SUMX(
        FILTER(
            PaymentSchedule,
            PaymentSchedule[CancellationStatus] IN {
                "Before Cancellation",
                "No Cancellation"
            }
        ),
        PaymentSchedule[Base_Installment_ProductA] +
        PaymentSchedule[Upgrade_Installment_ProductA]
    )

VAR RemainingPremium =
    CALCULATE(
        SUMX(
            FILTER(
                PaymentSchedule,
                PaymentSchedule[CancellationStatus] IN {
                    "After Cancellation",
                    "In Cancellation Month"
                }
                && PaymentSchedule[EventType] <> "Cancelled"
            ),
            PaymentSchedule[Base_Installment_ProductA] +
            PaymentSchedule[Upgrade_Installment_ProductA]
        ),
        USERELATIONSHIP(
            PaymentSchedule[CancellationEffectiveDate_YearMonthNum],
            dim_PymtDate[MonthYearNum]
        )
    )

VAR CancelledRowPremium =
    CALCULATE(
        SUMX(
            FILTER(
                PaymentSchedule,
                PaymentSchedule[EventType] = "Cancelled"
                    && PaymentSchedule[CancellationStatus] IN {
                        "In Cancellation Month",
                        "Renewal Cancellation"
                    }
            ),
            PaymentSchedule[Base_Installment_ProductA] +
            PaymentSchedule[Upgrade_Installment_ProductA]
        ),
        USERELATIONSHIP(
            PaymentSchedule[CancellationEffectiveDate_YearMonthNum],
            dim_PymtDate[MonthYearNum]
        )
    )

VAR LumpSum = CancelledRowPremium + RemainingPremium

RETURN
    RegularPayments + LumpSum
