DEFINE
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('dim_BDXDate'[MonthYearShort])),
			NOT('dim_BDXDate'[MonthYearShort] IN {BLANK()})
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL(
				ROLLUPGROUP(
					'dim_UWDate'[MonthYearShort],
					'dim_UWDate'[MonthYearNum],
					'dim_BDXDate'[MonthYearShort],
					'dim_BDXDate'[MonthYearNum]
				), "IsGrandTotalRowTotal"
			),
			__DS0FilterTable,
			"pl_payment_total", '_Measures'[pl_payment_total],
			"ipt_pl_payment_total", '_Measures'[ipt_pl_payment_total],
			"commission_pl_payment_total", '_Measures'[commission_pl_payment_total],
			"admin_fee_pa_pl_payment_total", '_Measures'[admin_fee_pa+pl_payment_total]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			502,
			__DS0Core,
			[IsGrandTotalRowTotal],
			0,
			'dim_UWDate'[MonthYearNum],
			1,
			'dim_UWDate'[MonthYearShort],
			1,
			'dim_BDXDate'[MonthYearNum],
			1,
			'dim_BDXDate'[MonthYearShort],
			1
		)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal] DESC,
	'dim_UWDate'[MonthYearNum],
	'dim_UWDate'[MonthYearShort],
	'dim_BDXDate'[MonthYearNum],
	'dim_BDXDate'[MonthYearShort]